// Dihasilkan dari Rust. Jangan disunting tangan.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Perintah pertama, dari Fase 0. Ia bertahan karena mode smoke memakainya
	 *  untuk membuktikan IPC bulat sebelum menyentuh basis data.
	 */
	halo: (nama: string) => __TAURI_INVOKE<Sapaan>("halo", { nama }),
	laporSinyal: (nama: string) => typedError<null, string>(__TAURI_INVOKE("lapor_sinyal", { nama })),
	buatWorkspace: (nama: string, jalur: string) => typedError<Workspace, Galat>(__TAURI_INVOKE("buat_workspace", { nama, jalur })),
	daftarWorkspace: () => typedError<Workspace[], Galat>(__TAURI_INVOKE("daftar_workspace")),
	buatSesi: (workspaceId: string, judul: string) => typedError<Sesi, Galat>(__TAURI_INVOKE("buat_sesi", { workspaceId, judul })),
	daftarSesi: (workspaceId: string) => typedError<Sesi[], Galat>(__TAURI_INVOKE("daftar_sesi", { workspaceId })),
	tambahPesan: (sesiId: string, peran: Peran, isi: string) => typedError<Pesan, Galat>(__TAURI_INVOKE("tambah_pesan", { sesiId, peran, isi })),
	daftarPesan: (sesiId: string) => typedError<Pesan[], Galat>(__TAURI_INVOKE("daftar_pesan", { sesiId })),
	/**
	 *  Menulis workspace, sesi, dan pesan, membacanya kembali, lalu membatalkan
	 *  seluruhnya. Transaksinya di-rollback saat `tx` jatuh, jadi tidak ada sisa
	 *  baris — tapi migrasi, foreign key, CHECK constraint, dan jalur baca-tulis
	 *  yang sesungguhnya semuanya benar-benar dilewati.
	 * 
	 *  Dipanggil saat aplikasi dibuka, bukan hanya di CI: basis data yang rusak
	 *  atau hanya-baca sebaiknya ketahuan sekarang, bukan saat pengguna menekan
	 *  tombol pertamanya.
	 */
	periksaBasisData: () => typedError<PeriksaDb, Galat>(__TAURI_INVOKE("periksa_basis_data")),
};

/* Types */
export type Galat = 
/**  Basis data menolak, gagal dibuka, atau migrasinya tidak jalan. */
{ jenis: "basisData"; pesan: string } | 
/**
 *  Yang diminta tidak ada. Dipisahkan dari BasisData karena antarmuka
 *  biasanya ingin memperlakukannya lain — bukan kegagalan, hanya kosong.
 */
{ jenis: "tidakDitemukan"; pesan: string } | 
/**  Masukan dari antarmuka tidak masuk akal sebelum menyentuh basis data. */
{ jenis: "masukanTakSah"; pesan: string };

export type Peran = "pengguna" | "asisten";

export type PeriksaDb = {
	tulisBacaUtuh: boolean,
	jumlahWorkspace: number,
	jumlahSesi: number,
	jumlahPesan: number,
};

export type Pesan = {
	id: string,
	sesiId: string,
	peran: Peran,
	isi: string,
	dibuatPada: number | null,
};

export type Sapaan = {
	pesan: string,
	platform: string,
	arsitektur: string,
	versiTauri: string,
	versiAplikasi: string,
};

export type Sesi = {
	id: string,
	workspaceId: string,
	judul: string,
	dibuatPada: number | null,
	diperbaruiPada: number | null,
};

/**
 *  Specta menolak mengekspor i64 ke TypeScript karena `number` kehilangan
 *  presisi di atas 2^53, dan penolakan itu benar sebagai aturan umum. Milidetik
 *  Unix adalah pengecualiannya: sekitar 1,7 x 10^12, empat ribu kali di bawah
 *  batas itu, dan baru menyentuhnya pada tahun 287396. Jadi tiap medan waktu
 *  menyatakan sendiri bahwa ia aman sebagai `number` — bukan lewat saklar global
 *  yang diam-diam ikut melonggarkan i64 lain yang kelak ditambahkan.
 */
export type Workspace = {
	id: string,
	nama: string,
	/**
	 *  Folder sungguhan di disk. Inilah yang membuat workspace bukan sekadar
	 *  baris basis data.
	 */
	jalur: string,
	dibuatPada: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

