// Generated from Rust. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  The first command, from Phase 0. It survives because smoke mode uses it to
	 *  prove the IPC round-trip before anything touches the database.
	 */
	hello: (name: string) => __TAURI_INVOKE<Greeting>("hello", { name }),
	reportSignal: (name: string) => typedError<null, string>(__TAURI_INVOKE("report_signal", { name })),
	smokeExpectations: () => __TAURI_INVOKE<SmokeExpectations>("smoke_expectations"),
	createWorkspace: (name: string, path: string) => typedError<Workspace, Error>(__TAURI_INVOKE("create_workspace", { name, path })),
	listWorkspaces: () => typedError<Workspace[], Error>(__TAURI_INVOKE("list_workspaces")),
	/**
	 *  Writes a workspace, reads it back, then rolls it away. The transaction is
	 *  rolled back when `tx` drops, so no rows are left behind — but the migrations
	 *  and the real read-write path are genuinely exercised.
	 * 
	 *  It used to write a session and a message too. Neither is ours to write any
	 *  more: OpenCode owns conversations, and the tables that held them are gone.
	 * 
	 *  Called when the application opens, not only in CI: a corrupt or read-only
	 *  database is better found now than when the user presses their first button.
	 */
	checkDatabase: () => typedError<DatabaseCheck, Error>(__TAURI_INVOKE("check_database")),
	engineStatus: () => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("engine_status")),
	startEngine: (workingDir: string) => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("start_engine", { workingDir })),
	stopEngine: () => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("stop_engine")),
	/**
	 *  The models actually available on the running engine.
	 * 
	 *  These must be asked for, not guessed: provider availability depends on the
	 *  engine's working directory. The same folder can offer dozens of models or
	 *  none, depending on whether OpenCode recognises it as a project.
	 */
	listModels: () => typedError<Model[], EngineError>(__TAURI_INVOKE("list_models")),
	/**
	 *  The catalogue, and which of it is usable.
	 * 
	 *  The reply carries no keys. `GET /provider` sends them in plain text, and the
	 *  type this deserialises into simply has no field for one — see `Provider` in
	 *  `engine::client`.
	 */
	listProviders: () => typedError<Providers, EngineError>(__TAURI_INVOKE("list_providers")),
	/**
	 *  Stores an API key for a provider, then restarts the engine.
	 * 
	 *  The restart is not housekeeping. The engine works out its providers and
	 *  models at startup and never again: measured, removing a provider's
	 *  credentials from a running engine left every one of its models still listed.
	 *  Without the restart, a key that was just added would connect nothing that the
	 *  model picker could see.
	 * 
	 *  `key` is never logged, never returned, and never stored on this side. It
	 *  exists in memory long enough to be handed to the engine.
	 */
	connectProvider: (providerId: string, key: string) => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("connect_provider", { providerId, key })),
	/**  Removes a provider's key, then restarts for the same reason. */
	disconnectProvider: (providerId: string) => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("disconnect_provider", { providerId })),
	/**
	 *  Every session the engine holds for `directory`, newest first.
	 * 
	 *  Rantai has no session table. OpenCode already stores sessions and their
	 *  messages, and that store is the one the model reads as context for the next
	 *  turn — keeping a second copy would mean the screen and the model could come
	 *  to disagree about what was said.
	 * 
	 *  `directory` is honoured for reading no matter where the engine itself is
	 *  working, so the whole sidebar is served by one process.
	 */
	listEngineSessions: (directory: string | null) => typedError<EngineSession[], EngineError>(__TAURI_INVOKE("list_engine_sessions", { directory })),
	/**  The conversation in a session, oldest first. */
	listEngineMessages: (engineSessionId: string) => typedError<Message_Serialize[], EngineError>(__TAURI_INVOKE("list_engine_messages", { engineSessionId })),
	/**
	 *  Creates an engine session with its model fixed on the session.
	 * 
	 *  The model must not simply be left out in real use: a session without one
	 *  falls back to the engine's default, and if that default cannot be used, the
	 *  failure never appears on the event stream at all — only in the engine's log.
	 *  The interface would appear to hang for no reason.
	 */
	createEngineSession: (model: {
	providerID: string,
	id: string,
} | null) => typedError<string, EngineError>(__TAURI_INVOKE("create_engine_session", { model })),
	/**
	 *  Sends a prompt, then streams the answer out as events. This command returns
	 *  once the prompt is accepted; the stream runs in the background until the
	 *  turn ends or is stopped.
	 * 
	 *  `model` is the model that answers *this* turn. A conversation can change
	 *  model between turns, so it travels with each prompt rather than living on
	 *  the session.
	 */
	sendPrompt: (engineSessionId: string, text: string, model: {
	providerID: string,
	id: string,
} | null) => typedError<null, EngineError>(__TAURI_INVOKE("send_prompt", { engineSessionId, text, model })),
	/**
	 *  Stops a conversation mid-flight — the engine side through `interrupt`, our
	 *  side by closing the stream. Both are needed: closing the stream alone leaves
	 *  the engine generating tokens into the void.
	 */
	stopConversation: (engineSessionId: string) => typedError<null, EngineError>(__TAURI_INVOKE("stop_conversation", { engineSessionId })),
	deepLinkStatus: () => __TAURI_INVOKE<DeepLinkStatus>("deep_link_status"),
	registerDeepLink: () => typedError<DeepLinkStatus, string>(__TAURI_INVOKE("register_deep_link")),
	/**
	 *  Opens the system browser. The second native touch, and the only other one.
	 * 
	 *  The Den sign-in sends the user to a web page, then waits for them to come back
	 *  through a deep link. Opening it inside the application's webview will not do:
	 *  the session and cookies there are not the user's browser session.
	 */
	openInBrowser: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_in_browser", { url })),
	launchLinks: () => __TAURI_INVOKE<string[]>("launch_links"),
	/**
	 *  Asks the endpoint whether there is a newer version. `None` means this is the
	 *  newest.
	 * 
	 *  A failure here is ordinary, not exceptional: the machine may be offline, or
	 *  GitHub may be unreachable. The message is returned as-is so the interface can
	 *  say what actually happened rather than "update check failed".
	 */
	checkForUpdate: () => typedError<{
	version: string,
	currentVersion: string,
	notes: string | null,
	publishedAt: string | null,
} | null, string>(__TAURI_INVOKE("check_for_update")),
	/**
	 *  Downloads and installs the update, then relaunches.
	 * 
	 *  The engine is stopped first, deliberately. Replacing the application's files
	 *  while a child process is running out of them is how an update leaves a
	 *  half-broken installation behind — and on Windows a running child can hold a
	 *  file lock that makes the replacement fail outright.
	 */
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
};

/** Events */
export const events = {
	chunk: makeEvent<Chunk>("chunk"),
	deepLink: makeEvent<DeepLink>("deep-link"),
	finished: makeEvent<Finished>("finished"),
};

/* Types */
/**
 *  One piece flowing from the engine to the screen.
 * 
 *  It is an event, not a return value — `invoke()` is request-response, and a
 *  token stream is not. Deriving `Event` carries the type into `bindings.ts`
 *  along with its listener, so the "never write a type twice" rule holds for
 *  events as well as commands.
 */
export type Chunk = {
	/**
	 *  Empty for events that belong to no session — the global stream also
	 *  carries `plugin.added`, `catalog.updated` and the like.
	 */
	engineSessionId: string | null,
	/**
	 *  The event name exactly as the engine gave it. Not translated here —
	 *  translating means guessing, and OpenCode's event shapes change between
	 *  versions.
	 */
	kind: string,
	/**
	 *  The raw event payload, as JSON.
	 * 
	 *  Deliberately exported as `unknown` rather than modelled. The shape of an
	 *  OpenCode event is decided by OpenCode and changes between versions;
	 *  writing it down here would promise a contract we do not control, and that
	 *  promise would quietly break on the next engine update. The interface
	 *  narrows it where it is actually used.
	 */
	payload: unknown,
};

export type DatabaseCheck = {
	writeReadIntact: boolean,
	workspaceCount: number,
};

/**
 *  Arrives when the system hands `openwork://…` to the application.
 * 
 *  Sent as a typed event rather than a `CustomEvent` through `webview.eval` the
 *  way the Rantai spike did. That spike had to imitate Electron's event shape
 *  because its interface had not changed; here there is nothing to imitate, and
 *  a typed event carries into `bindings.ts`.
 */
export type DeepLink = {
	urls: string[],
};

export type DeepLinkStatus = {
	scheme: string,
	/**
	 *  Whether the system really does hand this scheme to us. Asked of the
	 *  system, not assumed from a successful registration.
	 */
	registered: boolean,
	/**
	 *  Set when the system refuses to answer — in some environments (a headless
	 *  CI runner, say) the question itself fails, and that is not the same thing
	 *  as "not registered".
	 */
	error: string | null,
};

/**
 *  The shape an engine error takes when it crosses to the interface.
 * 
 *  `EngineFailure` deliberately does not derive `Type`: it is an internal type
 *  whose variants will grow, and that internal shape is not a contract. The
 *  contract is the message — and the message is where all the value of this
 *  phase's failure paths lives.
 */
export type EngineError = {
	message: string,
};

/**
 *  A session as the engine reports it.
 * 
 *  Rantai keeps no session table of its own. OpenCode already stores every one
 *  of these fields — title, model, cost, tokens, times — in its own SQLite, and
 *  it is the copy the model reads as context for the next turn. A second copy
 *  on our side would be the one on screen while the engine answered from the
 *  other, and the two would part company the first time a stream broke.
 */
export type EngineSession = {
	id: string,
	/**
	 *  The engine names a new session itself and renames it once there is
	 *  something to name it after, so this changes under us. It is read, never
	 *  written.
	 */
	title?: string,
	model?: Model | null,
	time: SessionTime,
	location?: SessionLocation | null,
};

export type EngineStatus = {
	running: boolean,
	address: string | null,
	binaryPath: string | null,
	source: string | null,
	uptimeSeconds: number | null,
	/**  The folder the running engine works in, if it is running. */
	workingDir: string | null,
};

export type Error = 
/**  The database refused, failed to open, or its migrations did not run. */
{ kind: "database"; message: string } | 
/**
 *  Input from the interface makes no sense before it ever reaches the
 *  database.
 */
{ kind: "invalidInput"; message: string };

/**  Emitted when the stream stops — finished on its own, cancelled, or failed. */
export type Finished = {
	engineSessionId: string,
	cancelled: boolean,
	error: string | null,
};

export type Greeting = {
	message: string,
	platform: string,
	arch: string,
	tauriVersion: string,
	appVersion: string,
};

/**
 *  One message in a conversation, as the interface sees it.
 * 
 *  Built from the engine's `{info, parts}` pair rather than deserialised
 *  straight into, so the interface keeps one flat shape and this file is the
 *  only place that knows the engine nests it. A user message carries its prose
 *  as `text`; an assistant message carries typed parts in `content`.
 */
export type Message = Message_Serialize | Message_Deserialize;

export type MessageTime = {
	created: number,
	completed?: number | null,
};

/**
 *  One message in a conversation, as the interface sees it.
 * 
 *  Built from the engine's `{info, parts}` pair rather than deserialised
 *  straight into, so the interface keeps one flat shape and this file is the
 *  only place that knows the engine nests it. A user message carries its prose
 *  as `text`; an assistant message carries typed parts in `content`.
 */
export type Message_Deserialize = {
	id: string,
	/**
	 *  `"user"` or `"assistant"`. Not an enum: the engine decides what kinds
	 *  exist, and a value we have not met should not fail the whole list.
	 */
	type: string,
	time: MessageTime,
	/**  The prose of a user message. */
	text: string | null,
	/**  Every part, in order. For a user message the prose is in `text` as well. */
	content: Part_Deserialize[],
	/**
	 *  The model this message was sent to, or answered by. It can differ from
	 *  turn to turn: a conversation is not fixed to one model.
	 */
	model: Model | null,
	/**  `"stop"`, `"tool-calls"`, and whatever else the engine reports. */
	finish: string | null,
	/**
	 *  Set when the turn failed or was stopped — `MessageAbortedError` for a
	 *  turn someone pressed Stop on.
	 */
	error: unknown | null,
};

/**
 *  One message in a conversation, as the interface sees it.
 * 
 *  Built from the engine's `{info, parts}` pair rather than deserialised
 *  straight into, so the interface keeps one flat shape and this file is the
 *  only place that knows the engine nests it. A user message carries its prose
 *  as `text`; an assistant message carries typed parts in `content`.
 */
export type Message_Serialize = {
	id: string,
	/**
	 *  `"user"` or `"assistant"`. Not an enum: the engine decides what kinds
	 *  exist, and a value we have not met should not fail the whole list.
	 */
	type: string,
	time: MessageTime,
	/**  The prose of a user message. */
	text: string | null,
	/**  Every part, in order. For a user message the prose is in `text` as well. */
	content: Part_Serialize[],
	/**
	 *  The model this message was sent to, or answered by. It can differ from
	 *  turn to turn: a conversation is not fixed to one model.
	 */
	model: Model | null,
	/**  `"stop"`, `"tool-calls"`, and whatever else the engine reports. */
	finish: string | null,
	/**
	 *  Set when the turn failed or was stopped — `MessageAbortedError` for a
	 *  turn someone pressed Stop on.
	 */
	error: unknown | null,
};

/**
 *  A model that is actually available, as reported by the engine.
 * 
 *  It must be asked for, never guessed: provider availability depends on the
 *  engine's working directory. The same folder can offer dozens of models or
 *  none, depending on whether OpenCode recognises it as a project.
 */
export type Model = {
	providerID: string,
	id: string,
};

/**
 *  A piece of an assistant message.
 * 
 *  `Other` is load-bearing. The engine's storage holds `step-start` and
 *  `step-finish` alongside these, and will hold kinds that do not exist yet —
 *  an enum without a catch-all would fail to parse the whole conversation the
 *  first time one appeared.
 */
export type Part = Part_Serialize | Part_Deserialize;

/**
 *  A piece of an assistant message.
 * 
 *  `Other` is load-bearing. The engine's storage holds `step-start` and
 *  `step-finish` alongside these, and will hold kinds that do not exist yet —
 *  an enum without a catch-all would fail to parse the whole conversation the
 *  first time one appeared.
 */
export type Part_Deserialize = ({ text: {
	type: "text",
	text?: string,
} }) & { other?: never; reasoning?: never; tool?: never } | ({ reasoning: {
	type: "reasoning",
	text?: string,
} }) & { other?: never; text?: never; tool?: never } | ({ tool: {
	type: "tool",
	tool: string,
	callID: string,
	state: ToolState,
} }) & { other?: never; reasoning?: never; text?: never } | ({ other: {
	type: string,
} }) & { reasoning?: never; text?: never; tool?: never };

/**
 *  A piece of an assistant message.
 * 
 *  `Other` is load-bearing. The engine's storage holds `step-start` and
 *  `step-finish` alongside these, and will hold kinds that do not exist yet —
 *  an enum without a catch-all would fail to parse the whole conversation the
 *  first time one appeared.
 */
export type Part_Serialize = ({ type: "text"; text: string }) & { callID?: never; state?: never; tool?: never } | ({ type: "reasoning"; text: string }) & { callID?: never; state?: never; tool?: never } | ({ type: "tool"; tool: string; callID: string; state: ToolState }) & { text?: never } | ({ type: "other" }) & { callID?: never; state?: never; text?: never; tool?: never };

export type PersistenceCheck = {
	/**  "write" on the first run, "read" on the second. */
	mode: string,
	/**
	 *  The same marker on both runs, so what is looked for is exactly what was
	 *  written.
	 */
	marker: string,
};

/**
 *  A provider in the engine's catalogue.
 * 
 *  **There is deliberately no `key` field, and one must never be added.**
 *  `GET /provider` returns the API key in plain text for every provider that has
 *  one. serde drops fields we do not declare, so the key stops here — it never
 *  reaches `bindings.ts`, the screen, a log line, or an error message. Declaring
 *  it "for completeness" would put a live credential on all four.
 */
export type Provider = {
	id: string,
	name?: string,
	/**
	 *  The environment variables this provider would read a key from. Shown so
	 *  someone who would rather not paste a key into an application can see
	 *  which variable to set instead.
	 */
	env?: string[],
};

/**  The catalogue, and which of it can actually be used. */
export type Providers = {
	all: Provider[],
	/**
	 *  Provider ids the engine considers usable right now. This is the engine's
	 *  own answer, not ours — a provider can be connected through a key we
	 *  stored, through an environment variable, or by needing nothing at all.
	 */
	connected: string[],
};

/**
 *  Which folder the session belongs to. This is how a session is tied to a
 *  workspace: there is no id linking them, only the path.
 */
export type SessionLocation = {
	directory?: string | null,
};

export type SessionTime = {
	created: number,
	updated: number,
};

/**
 *  Told to the interface so it knows which checks to run. Without this the
 *  interface would have to guess — and guessing on a failure path is exactly how
 *  a test becomes flawed without anyone noticing.
 */
export type SmokeExpectations = {
	enabled: boolean,
	/**  "absent" or "present", when CI asks for either. */
	engine: string | null,
	/**
	 *  When set, the interface must prove this grant is the one that arrived by
	 *  deep link.
	 */
	deepLink: string | null,
	/**  When set, the interface must write or read data under this marker. */
	persistence: PersistenceCheck | null,
};

export type ToolState = {
	/**  `"pending"`, `"running"`, `"completed"`, `"error"`. */
	status: string,
	title?: string | null,
	/**
	 *  Left as JSON: every tool has its own argument shape, and writing them
	 *  down here would promise a contract the tools own, not us.
	 */
	input?: unknown | null,
	output?: string | null,
};

export type UpdateAvailable = {
	version: string,
	currentVersion: string,
	notes: string | null,
	publishedAt: string | null,
};

/**
 *  Specta refuses to export i64 to TypeScript because `number` loses precision
 *  above 2^53, and as a general rule that refusal is right. Unix milliseconds
 *  are the exception: around 1.7 x 10^12, four thousand times under the limit,
 *  and they only reach it in the year 287396. So each timestamp field declares
 *  for itself that it is safe as a `number` — rather than a global switch that
 *  would quietly loosen any other i64 added later.
 * 
 *  Declared as `specta_typescript::Number`, not `f64`. Both become `number` in
 *  TypeScript, but `f64` becomes `number | null` — because JSON turns NaN and
 *  Infinity into `null`, and specta is right to account for it. Timestamps are
 *  never NaN, so that `| null` forces every caller to handle something that
 *  cannot happen. A lie in that direction costs just as much.
 */
export type Workspace = {
	id: string,
	name: string,
	/**
	 *  A real folder on disk. This is what makes a workspace more than a row in
	 *  a database.
	 */
	path: string,
	createdAt: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

