// Generated from Rust. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  The first command, from Phase 0. It survives because smoke mode uses it to
	 *  prove the IPC round-trip before anything touches the database.
	 */
	hello: (name: string) => __TAURI_INVOKE<Greeting>("hello", { name }),
	reportSignal: (name: string) => typedError<null, string>(__TAURI_INVOKE("report_signal", { name })),
	smokeExpectations: () => __TAURI_INVOKE<SmokeExpectations>("smoke_expectations"),
	createWorkspace: (name: string, path: string) => typedError<Workspace, Error>(__TAURI_INVOKE("create_workspace", { name, path })),
	listWorkspaces: () => typedError<Workspace[], Error>(__TAURI_INVOKE("list_workspaces")),
	createSession: (workspaceId: string, title: string) => typedError<Session, Error>(__TAURI_INVOKE("create_session", { workspaceId, title })),
	listSessions: (workspaceId: string) => typedError<Session[], Error>(__TAURI_INVOKE("list_sessions", { workspaceId })),
	addMessage: (sessionId: string, role: Role, content: string) => typedError<Message, Error>(__TAURI_INVOKE("add_message", { sessionId, role, content })),
	listMessages: (sessionId: string) => typedError<Message[], Error>(__TAURI_INVOKE("list_messages", { sessionId })),
	/**
	 *  Writes a workspace, a session and a message, reads them back, then rolls all
	 *  of it away. The transaction is rolled back when `tx` drops, so no rows are
	 *  left behind — but the migrations, the foreign keys, the CHECK constraints and
	 *  the real read-write path are all genuinely exercised.
	 * 
	 *  Called when the application opens, not only in CI: a corrupt or read-only
	 *  database is better found now than when the user presses their first button.
	 */
	checkDatabase: () => typedError<DatabaseCheck, Error>(__TAURI_INVOKE("check_database")),
	engineStatus: () => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("engine_status")),
	startEngine: (workingDir: string) => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("start_engine", { workingDir })),
	stopEngine: () => typedError<EngineStatus, EngineError>(__TAURI_INVOKE("stop_engine")),
	/**
	 *  The models actually available on the running engine.
	 * 
	 *  These must be asked for, not guessed: provider availability depends on the
	 *  engine's working directory. The same folder can offer dozens of models or
	 *  none, depending on whether OpenCode recognises it as a project.
	 */
	listModels: () => typedError<Model[], EngineError>(__TAURI_INVOKE("list_models")),
	/**
	 *  Creates an engine session with its model fixed on the session.
	 * 
	 *  The model must not simply be left out in real use: a session without one
	 *  falls back to the engine's default, and if that default cannot be used, the
	 *  failure never appears on the event stream at all — only in the engine's log.
	 *  The interface would appear to hang for no reason.
	 */
	createEngineSession: (model: {
	providerID: string,
	id: string,
} | null) => typedError<string, EngineError>(__TAURI_INVOKE("create_engine_session", { model })),
	/**
	 *  Sends a prompt, then streams the answer out as events. This command returns
	 *  immediately; the stream runs in the background until it finishes or is
	 *  stopped.
	 */
	sendPrompt: (engineSessionId: string, text: string) => typedError<null, EngineError>(__TAURI_INVOKE("send_prompt", { engineSessionId, text })),
	/**
	 *  Stops a conversation mid-flight — the engine side through `interrupt`, our
	 *  side by closing the stream. Both are needed: closing the stream alone leaves
	 *  the engine generating tokens into the void.
	 */
	stopConversation: (engineSessionId: string) => typedError<null, EngineError>(__TAURI_INVOKE("stop_conversation", { engineSessionId })),
	deepLinkStatus: () => __TAURI_INVOKE<DeepLinkStatus>("deep_link_status"),
	registerDeepLink: () => typedError<DeepLinkStatus, string>(__TAURI_INVOKE("register_deep_link")),
	/**
	 *  Opens the system browser. The second native touch, and the only other one.
	 * 
	 *  The Den sign-in sends the user to a web page, then waits for them to come back
	 *  through a deep link. Opening it inside the application's webview will not do:
	 *  the session and cookies there are not the user's browser session.
	 */
	openInBrowser: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_in_browser", { url })),
	launchLinks: () => __TAURI_INVOKE<string[]>("launch_links"),
};

/** Events */
export const events = {
	chunk: makeEvent<Chunk>("chunk"),
	deepLink: makeEvent<DeepLink>("deep-link"),
	finished: makeEvent<Finished>("finished"),
};

/* Types */
/**
 *  One piece flowing from the engine to the screen.
 * 
 *  It is an event, not a return value — `invoke()` is request-response, and a
 *  token stream is not. Deriving `Event` carries the type into `bindings.ts`
 *  along with its listener, so the "never write a type twice" rule holds for
 *  events as well as commands.
 */
export type Chunk = {
	/**
	 *  Empty for events that belong to no session — the global stream also
	 *  carries `plugin.added`, `catalog.updated` and the like.
	 */
	engineSessionId: string | null,
	/**
	 *  The event name exactly as the engine gave it. Not translated here —
	 *  translating means guessing, and OpenCode's event shapes change between
	 *  versions.
	 */
	kind: string,
	/**
	 *  The raw event payload, as JSON.
	 * 
	 *  Deliberately exported as `unknown` rather than modelled. The shape of an
	 *  OpenCode event is decided by OpenCode and changes between versions;
	 *  writing it down here would promise a contract we do not control, and that
	 *  promise would quietly break on the next engine update. The interface
	 *  narrows it where it is actually used.
	 */
	payload: unknown,
};

export type DatabaseCheck = {
	writeReadIntact: boolean,
	workspaceCount: number,
	sessionCount: number,
	messageCount: number,
};

/**
 *  Arrives when the system hands `openwork://…` to the application.
 * 
 *  Sent as a typed event rather than a `CustomEvent` through `webview.eval` the
 *  way the Rantai spike did. That spike had to imitate Electron's event shape
 *  because its interface had not changed; here there is nothing to imitate, and
 *  a typed event carries into `bindings.ts`.
 */
export type DeepLink = {
	urls: string[],
};

export type DeepLinkStatus = {
	scheme: string,
	/**
	 *  Whether the system really does hand this scheme to us. Asked of the
	 *  system, not assumed from a successful registration.
	 */
	registered: boolean,
	/**
	 *  Set when the system refuses to answer — in some environments (a headless
	 *  CI runner, say) the question itself fails, and that is not the same thing
	 *  as "not registered".
	 */
	error: string | null,
};

/**
 *  The shape an engine error takes when it crosses to the interface.
 * 
 *  `EngineFailure` deliberately does not derive `Type`: it is an internal type
 *  whose variants will grow, and that internal shape is not a contract. The
 *  contract is the message — and the message is where all the value of this
 *  phase's failure paths lives.
 */
export type EngineError = {
	message: string,
};

export type EngineStatus = {
	running: boolean,
	address: string | null,
	binaryPath: string | null,
	source: string | null,
	uptimeSeconds: number | null,
};

export type Error = 
/**  The database refused, failed to open, or its migrations did not run. */
{ kind: "database"; message: string } | 
/**
 *  What was asked for does not exist. Kept apart from `Database` because the
 *  interface usually wants to treat it differently — not a failure, just
 *  empty.
 */
{ kind: "notFound"; message: string } | 
/**
 *  Input from the interface makes no sense before it ever reaches the
 *  database.
 */
{ kind: "invalidInput"; message: string };

/**  Emitted when the stream stops — finished on its own, cancelled, or failed. */
export type Finished = {
	engineSessionId: string,
	cancelled: boolean,
	error: string | null,
};

export type Greeting = {
	message: string,
	platform: string,
	arch: string,
	tauriVersion: string,
	appVersion: string,
};

export type Message = {
	id: string,
	sessionId: string,
	role: Role,
	content: string,
	createdAt: number,
};

/**
 *  A model that is actually available, as reported by the engine.
 * 
 *  It must be asked for, never guessed: provider availability depends on the
 *  engine's working directory. The same folder can offer dozens of models or
 *  none, depending on whether OpenCode recognises it as a project.
 */
export type Model = {
	providerID: string,
	id: string,
};

export type PersistenceCheck = {
	/**  "write" on the first run, "read" on the second. */
	mode: string,
	/**
	 *  The same marker on both runs, so what is looked for is exactly what was
	 *  written.
	 */
	marker: string,
};

export type Role = "user" | "assistant";

export type Session = {
	id: string,
	workspaceId: string,
	title: string,
	createdAt: number,
	updatedAt: number,
};

/**
 *  Told to the interface so it knows which checks to run. Without this the
 *  interface would have to guess — and guessing on a failure path is exactly how
 *  a test becomes flawed without anyone noticing.
 */
export type SmokeExpectations = {
	enabled: boolean,
	/**  "absent" or "present", when CI asks for either. */
	engine: string | null,
	/**
	 *  When set, the interface must prove this grant is the one that arrived by
	 *  deep link.
	 */
	deepLink: string | null,
	/**  When set, the interface must write or read data under this marker. */
	persistence: PersistenceCheck | null,
};

/**
 *  Specta refuses to export i64 to TypeScript because `number` loses precision
 *  above 2^53, and as a general rule that refusal is right. Unix milliseconds
 *  are the exception: around 1.7 x 10^12, four thousand times under the limit,
 *  and they only reach it in the year 287396. So each timestamp field declares
 *  for itself that it is safe as a `number` — rather than a global switch that
 *  would quietly loosen any other i64 added later.
 * 
 *  Declared as `specta_typescript::Number`, not `f64`. Both become `number` in
 *  TypeScript, but `f64` becomes `number | null` — because JSON turns NaN and
 *  Infinity into `null`, and specta is right to account for it. Timestamps are
 *  never NaN, so that `| null` forces every caller to handle something that
 *  cannot happen. A lie in that direction costs just as much.
 */
export type Workspace = {
	id: string,
	name: string,
	/**
	 *  A real folder on disk. This is what makes a workspace more than a row in
	 *  a database.
	 */
	path: string,
	createdAt: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

